"""
Django settings for rit_academic_system project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
DATA_UPLOAD_MAX_NUMBER_FIELDS = None


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$al$1%9o#dgtt-@l6379mj7!efn3s9tedn5efq$ic*k5vsffvq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

LOGIN_URL = 'login_view'

CSRF_TRUSTED_ORIGINS = [
    "https://erp.ramcoad.com",
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_accounts',
    'course_management',
    'examination_management',
    'student_management',
    'faculty_management',
    'fee_management',
    'nba',
    'faculty_leave_management',
    'feedback_management',
    'learning_management_system',
    'library_management',
    'data_center_management',
    'stock_management',
    'chatbot',
    'mock_interview',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'user_accounts.middleware.AuditLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rit_academic_system.urls'


X_FRAME_OPTIONS = 'ALLOWALL'

import os
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'faculty_management.context_processors.profile_completion',
            ],
        },
    },
]

WSGI_APPLICATION = 'rit_academic_system.wsgi.application'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# # EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_SSL = True

# # Gmail credentials
# EMAIL_HOST_USER = 'ritegovernance@ritrjpm.ac.in'
# EMAIL_HOST_PASSWORD = 'gmcs gqpv xait trgx'  # Replace with your Gmail App Password

# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
# SERVER_EMAIL = EMAIL_HOST_USER
# CONTACT_FORM_EMAIL = EMAIL_HOST_USER
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Replace with your SMTP server address
EMAIL_PORT = 465  # Common port for TLS
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False  # Use TLS for secure connection
EMAIL_HOST_USER = 'ritegovernance@ritrjpm.ac.in'  # Your email address
EMAIL_HOST_PASSWORD = 'gmcs gqpv xait trgx'  # Your email password or app-specific password
DEFAULT_FROM_EMAIL = 'ritegovernance@ritrjpm.ac.in'  # Default sender for emails
# SEND_CONFIRMATION_EMAIL = True

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ramco_academic_system',
#         'USER': 'root',
#         'PASSWORD': '',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ramco_academic_system',  # Replace with your actual default DB
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        },
    },
    'rit_approval_system': {  # Define this database properly
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rit_approval_system',  # This must match the actual MySQL database name
        'USER': 'root',  # Your MySQL username
        'PASSWORD': '',  # Your MySQL password (if any)
        'HOST': '127.0.0.1',  # Use 'localhost' or '127.0.0.1'
        'PORT': '3306',  # Default MySQL port
    },
    
    'rit_cgpatrack': {  # Define this database properly
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rit_cgpatrack',  # This must match the actual MySQL database name
        'USER': 'root',  # Your MySQL username
        'PASSWORD': '',  # Your MySQL password (if any)
        'HOST': '127.0.0.1',  # Use 'localhost' or '127.0.0.1'
        'PORT': '3306',  # Default MySQL port
        
    },
    
    'rit_academic_system': {  # Define this database properly
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rit_academic_system',  # This must match the actual MySQL database name
        'USER': 'root',  # Your MySQL username
        'PASSWORD': '',  # Your MySQL password (if any)
        'HOST': '127.0.0.1',  # Use 'localhost' or '127.0.0.1'
        'PORT': '3306',  # Default MySQL port
        
    },
    'admissionform1': {  # Define this database properly
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'collegeadmissiondb',  # This must match the actual MySQL database name
        'USER': 'root',  # Your MySQL username
        'PASSWORD': '',  # Your MySQL password (if any)
        'HOST': '127.0.0.1',  # Use 'localhost' or '127.0.0.1'
        'PORT': '3306',  # Default MySQL port

    },
    
    'attendance_db': {
        'ENGINE': 'mssql',
        'NAME': 'SmartOfficedb',
        'USER': 'sa',
        'PASSWORD': '123456',
        'HOST': '172.16.1.5',
        'PORT': '1433',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes;'
        },
    },
    'erp_rit': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ritrjpme_ele2021',
        'USER': 'ritrjpme_root1',
        'PASSWORD': 'ritcse@2017',
        'HOST': '68.183.247.48',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
}




AUTHENTICATION_BACKENDS = [
    'user_accounts.auth.EmployeeIDBackend',  # Use your custom backend
    'django.contrib.auth.backends.ModelBackend',  # Optional fallback
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# DATABASE_ROUTERS = ['user_accounts.db_router.RemoteUserRouter']
# settings.py
# DATABASE_ROUTERS = ['user_accounts.db_router.RemoteUserRouter']

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'




STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




#  academic year

from datetime import date

def get_academic_year():
    """Get current academic year based on June boundary"""
    today = date.today()
    if today.month >= 6:
        return f"{today.year}-{today.year + 1}"
    return f"{today.year - 1}-{today.year}"

ACADEMIC_YEAR = get_academic_year()



# Z AI Configuration for LMS Chat
GEMINI_API_KEY = "AIzaSyCifV9HkhSZT3vWK7ZbzDevfmGBWp2wx-s"

# Ollama (local network)
OLLAMA_BASE_URL = "http://172.16.71.114:11434/v1"
OLLAMA_MODEL = "gemma3:4b"
GEMINI_MODEL = "gemini-2.5-flash"




import os
MOCK_INTERVIEW = {
    'OLLAMA_BASE_URL': os.environ.get(
        'MOCK_INTERVIEW_OLLAMA_BASE_URL',
        'http://127.0.0.1:11434',
    ),
    'OLLAMA_MODEL': os.environ.get(
        'MOCK_INTERVIEW_OLLAMA_MODEL',
        'qwen3:8b',
    ),
    'OLLAMA_INTERACTIVE_MODEL': os.environ.get(
        'MOCK_INTERVIEW_OLLAMA_INTERACTIVE_MODEL',
        'qwen3:1.7b',
    ),
    'OLLAMA_REPORT_MODEL': os.environ.get(
        'MOCK_INTERVIEW_OLLAMA_REPORT_MODEL',
        'qwen3:1.7b',
    ),
    'OLLAMA_TIMEOUT': float(os.environ.get('MOCK_INTERVIEW_OLLAMA_TIMEOUT', '120')),
    'OLLAMA_CONTEXT_TOKENS': int(
        os.environ.get('MOCK_INTERVIEW_OLLAMA_CONTEXT_TOKENS', '4096')
    ),
    'OLLAMA_MAX_OUTPUT_TOKENS': int(
        os.environ.get('MOCK_INTERVIEW_OLLAMA_MAX_OUTPUT_TOKENS', '1024')
    ),
    'OLLAMA_THINK': os.environ.get(
        'MOCK_INTERVIEW_OLLAMA_THINK',
        'false',
    ).lower() in {'1', 'true', 'yes'},
    'WHISPER_MODEL': os.environ.get(
        'MOCK_INTERVIEW_WHISPER_MODEL',
        'large-v3-turbo',
    ),
    'WHISPER_DEVICE': os.environ.get('MOCK_INTERVIEW_WHISPER_DEVICE', 'cpu'),
    'WHISPER_COMPUTE_TYPE': os.environ.get(
        'MOCK_INTERVIEW_WHISPER_COMPUTE_TYPE',
        'int8',
    ),
    'WHISPER_BEAM_SIZE': int(
        os.environ.get('MOCK_INTERVIEW_WHISPER_BEAM_SIZE', '1')
    ),
    'WHISPER_REPETITION_PENALTY': float(
        os.environ.get('MOCK_INTERVIEW_WHISPER_REPETITION_PENALTY', '1.15')
    ),
    'WHISPER_NO_REPEAT_NGRAM_SIZE': int(
        os.environ.get('MOCK_INTERVIEW_WHISPER_NO_REPEAT_NGRAM_SIZE', '4')
    ),
    'KOKORO_VOICE': os.environ.get('MOCK_INTERVIEW_KOKORO_VOICE', 'af_heart'),
    'KOKORO_ONNX_MODEL': os.environ.get(
        'MOCK_INTERVIEW_KOKORO_ONNX_MODEL',
        os.path.join(
            BASE_DIR,
            'mock_interview',
            'model_data',
            'kokoro',
            'kokoro-v1.0.onnx',
        ),
    ),
    'KOKORO_ONNX_VOICES': os.environ.get(
        'MOCK_INTERVIEW_KOKORO_ONNX_VOICES',
        os.path.join(
            BASE_DIR,
            'mock_interview',
            'model_data',
            'kokoro',
            'voices-v1.0.bin',
        ),
    ),
    'TTS_BACKEND': os.environ.get('MOCK_INTERVIEW_TTS_BACKEND', 'auto'),
    'PIPER_VOICE_MODEL': os.environ.get(
        'MOCK_INTERVIEW_PIPER_VOICE_MODEL',
        os.path.join(
            BASE_DIR,
            'mock_interview',
            'model_data',
            'piper',
            'en_US-lessac-medium.onnx',
        ),
    ),
    'TTS_SPEED': float(os.environ.get('MOCK_INTERVIEW_TTS_SPEED', '0.95')),
    'MAX_RESUME_BYTES': int(
        os.environ.get('MOCK_INTERVIEW_MAX_RESUME_BYTES', str(5 * 1024 * 1024))
    ),
    'MAX_ANSWER_AUDIO_BYTES': int(
        os.environ.get(
            'MOCK_INTERVIEW_MAX_ANSWER_AUDIO_BYTES',
            str(25 * 1024 * 1024),
        )
    ),
    'ALLOW_DETERMINISTIC_FALLBACK': os.environ.get(
        'MOCK_INTERVIEW_ALLOW_DETERMINISTIC_FALLBACK',
        'true',
    ).lower() in {'1', 'true', 'yes'},
}

# RAG pipeline configuration for document-grounded interviews
RAG_CONFIG = {
    'QDRANT_URL': os.environ.get(
        'RAG_QDRANT_URL',
        'http://127.0.0.1:6333',
    ),
    'QDRANT_COLLECTION': os.environ.get(
        'RAG_QDRANT_COLLECTION',
        'mock_interview_documents',
    ),
    'EMBEDDING_MODEL': os.environ.get(
        'RAG_EMBEDDING_MODEL',
        'BAAI/bge-m3',
    ),
    'EMBEDDING_DIMENSION': int(
        os.environ.get('RAG_EMBEDDING_DIMENSION', '1024')
    ),
    'CHUNK_SIZE': int(os.environ.get('RAG_CHUNK_SIZE', '512')),
    'CHUNK_OVERLAP': int(os.environ.get('RAG_CHUNK_OVERLAP', '64')),
    'TOP_K_CHUNKS': int(os.environ.get('RAG_TOP_K_CHUNKS', '5')),
    'MAX_DOCUMENT_BYTES': int(
        os.environ.get('RAG_MAX_DOCUMENT_BYTES', str(50 * 1024 * 1024))
    ),
    'ALLOWED_DOCUMENT_TYPES': [
        'application/pdf',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'text/plain',
    ],
}
